name: Good Good Study <--> Day Day Up 
markdown: redcarpet
pygments: true
permalink: date
google_analytics_code: UA-67869111-1 
url: https://freeman0211.github.io/
exclude:
- config.ru
- Gemfile
- Gemfile.lock
- Rakefile
- README.markdown
- bin
- public
- vendor
